graph TD
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/main.do"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/tech"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/tech"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/design"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/service"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/corporate"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/people"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/benefits"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/rcrt/list.do"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/mem/login.do"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/bbs/faq.do"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/rcrt/list.do#n"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/tech"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/design"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/service"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/corporate"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/people"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/cnts/benefits"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/rcrt/list.do"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/mem/login.do"
    "https://recruit.snowcorp.com/rcrt/list.do" --> |Href| "https://recruit.snowcorp.com/bbs/faq.do"
    "https://recruit.snowcorp.com/rcrt/list.do_link_21"[Link: 21] --> |Onclick| "Threaded Task"
    "https://recruit.snowcorp.com/rcrt/list.do_link_28"[Link: 28] --> |Onclick| "Threaded Task"
    "https://recruit.snowcorp.com/rcrt/list.do_link_35"[Link: 35] --> |Onclick| "Threaded Task"
    "https://recruit.snowcorp.com/rcrt/list.do_link_42"[Link: 42] --> |Onclick| "Threaded Task"
    "https://recruit.snowcorp.com/rcrt/list.do_link_49"[Link: 49] --> |Onclick| "Threaded Task"
    "https://recruit.snowcorp.com/rcrt/list.do_link_56"[Link: 56] --> |Onclick| "Threaded Task"
